### ISSUE TITLE
USER STORY: enhance interactions and widen the community the user

### ISSUE THREAD

**Issue by Harriss1989** [Harriss1989/My-Firrst-Agile-Project#4]
In order to vote on best time for running, best track… etc. as a user of the site and part of the running community , I can use the poll on the home page to vote on the different topics available and choose to vote anonymously and also add comments.

### Acceptance Criteria:

- The options should be available as a checkbox.
- A comment box should be underneath to give the users ability to express there opinions.
- A submit button underneath the comment box.
- The option to add user name or stay anonymous in a check box next to the submit button.

### Tasks

- [ ] Create the poll form on home page.
- [ ] Create checkbox to hold available options time , places ect.
- [ ] Create comment box and submit button.
- [ ] Create checkbox to add user name or stay anonymous.

**Comment by Harriss1989** [comment]
this is completed
